# These are supported funding model platforms for Werracle & pCwOrM

# GitHub Sponsors username (will link once sponsor profile is approved)
github: [pCwOrM]

# Custom sponsorship, grant, and contribution links
custom:
  - https://github.com/pCwOrM/werracle#sponsor--grant-funding
  - https://pcworm.github.io/werracle/
